"""added role column

Revision ID: 2608702a5c00
Revises: 7ab36fe5338a
Create Date: 2023-04-10 16:39:09.369845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2608702a5c00'
down_revision = '7ab36fe5338a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_member', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
